### PR TITLE
Fix bug with an empty carousel

### PR DESCRIPTION
**Pull request by stof**
This is applying https://github.com/maaaaark/bcSwipe/pull/6 to this fork.

### CODE REVIEW

**Comment by stof** [comment]
btw, your dist file is broken. browserify strips most of the code considering it is dead code (probably because there is no exports)

**Comment by briggySmalls** [comment]
Thanks!

**Comment by stof** [comment]
@briggySmalls any chance to publish that fix on npm ?

**Comment by briggySmalls** [comment]
Published! 🙏 

Sorry. It's been a long time since I looked at this 😓

**Pull request merged**
