### PR TITLE
Add the main field in package.json

### PR DESCRIPTION
**Pull request by stof**
Some tools (for instance the no-unresolved rule of eslint-plugin-import) don't support using the browser field instead of main

### CODE REVIEW

**Review by yguedidi — APPROVED** [review]

**Comment by stof** [comment]
@briggySmalls any chance to merge this ?

**Comment by briggySmalls** [comment]
I'm ever so sorry @stof. I'm not very attentive here.

I really appreciate your contribution!

**Comment by stof** [comment]
@briggySmalls thanks for the merge. It would be great to release this on the npm registry.

**Comment by briggySmalls** [comment]
Released!

**Comment by stof** [comment]
thanks

**Pull request merged**
